services:
  - type: web
    name: o2-menu
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_ORIGIN
        sync: false                 # https://o2bot.onrender.com
      - key: NEXT_PUBLIC_USE_BOT_PROXY
        value: "1"
